---
# Node Exporter and other exporters setup tasks
- name: Deploy Node Exporter container
  community.docker.docker_container:
    name: node-exporter-{{ deployment_environment | default('local') }}
    image: "prom/node-exporter:{{ node_exporter_version }}"
    state: started
    restart_policy: "{{ monitoring_restart_policy }}"
    ports:
      - "{{ node_exporter_port }}:9100"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - name: "{{ monitoring_docker_network }}"
    user: "65534:65534"  # nobody user
  when: node_exporter_enabled | default(true)

- name: Deploy cAdvisor container (container metrics)
  community.docker.docker_container:
    name: cadvisor-{{ deployment_environment | default('local') }}
    image: "gcr.io/cadvisor/cadvisor:latest"
    state: started
    restart_policy: "{{ monitoring_restart_policy }}"
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    devices:
      - "/dev/kmsg:/dev/kmsg"
    privileged: yes
    networks:
      - name: "{{ monitoring_docker_network }}"
  when: cadvisor_enabled | default(true)