---
collections:
  - name: community.docker
    version: ">=3.4.0"
  - name: containers.podman
    version: ">=1.10.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"