---
# Deployment Engineering Strategies Configuration
# Defines standardized deployment patterns and configurations

deployment_strategies:
  blue_green:
    name: "Blue-Green Deployment"
    description: "Zero-downtime deployment with instant rollback capability"
    switch_validation:
      - health_check
      - smoke_tests
      - traffic_routing_test
    rollback_triggers:
      - error_rate_threshold: "1%"
      - response_time_threshold: "500ms"
      - cpu_usage_threshold: "80%"
      - memory_usage_threshold: "85%"
    monitoring_duration: "5m"
    
  canary:
    name: "Canary Deployment"
    description: "Progressive traffic shifting with automated rollback"
    traffic_steps: [5, 10, 25, 50, 100]
    step_duration: "10m"
    success_criteria:
      - error_rate_max: "0.5%"
      - response_time_p99_max: "300ms"
      - success_rate_min: "99.9%"
    rollback_triggers:
      - error_spike: "2x baseline"
      - latency_spike: "1.5x baseline"
      - manual_trigger: true
      
  rolling:
    name: "Rolling Deployment"
    description: "Gradual instance replacement with health validation"
    max_unavailable: "25%"
    max_surge: "25%"
    health_check_timeout: "30s"
    rollout_timeout: "10m"
    
  feature_flag:
    name: "Feature Flag Deployment"
    description: "Feature toggle-based progressive rollout"
    default_enabled: false
    rollout_strategy: "percentage"
    user_targeting:
      - internal_users
      - beta_users
      - production_users
    monitoring_metrics:
      - feature_usage_rate
      - conversion_rate
      - error_rate_by_feature

# SLI/SLO Definitions for Deployment Engineering
sli_definitions:
  deployment_frequency:
    name: "Deployment Frequency"
    description: "Number of deployments per day"
    target: ">= 10/day"
    measurement: "count of successful deployments / day"
    
  lead_time:
    name: "Lead Time for Changes"
    description: "Time from commit to production"
    target: "< 1 hour"
    measurement: "commit timestamp to production deployment timestamp"
    
  mttr:
    name: "Mean Time to Recovery"
    description: "Time to recover from failures"
    target: "< 30 minutes"
    measurement: "incident start to resolution timestamp"
    
  change_failure_rate:
    name: "Change Failure Rate"
    description: "Percentage of deployments causing failures"
    target: "< 5%"
    measurement: "failed deployments / total deployments * 100"
    
  availability:
    name: "Service Availability"
    description: "Percentage of uptime"
    target: ">= 99.9%"
    measurement: "successful requests / total requests * 100"

# Quality Gates Configuration
quality_gates:
  security:
    vulnerability_scanning:
      enabled: true
      fail_on: ["CRITICAL", "HIGH"]
      tools: ["trivy", "snyk", "owasp-dependency-check"]
    
    secret_scanning:
      enabled: true
      patterns: ["api_keys", "passwords", "tokens"]
      
    compliance_checks:
      enabled: true
      standards: ["PCI-DSS", "SOX", "GDPR"]
      
  performance:
    load_testing:
      enabled: true
      thresholds:
        response_time_p95: "200ms"
        error_rate: "0.1%"
        throughput_min: "1000 rps"
        
    resource_limits:
      cpu_max: "80%"
      memory_max: "85%"
      disk_usage_max: "75%"
      
  reliability:
    chaos_engineering:
      enabled: false  # Enable for advanced teams
      scenarios:
        - "pod_failure"
        - "network_latency"
        - "disk_stress"
        
    health_checks:
      startup_probe: true
      readiness_probe: true
      liveness_probe: true
      
# Rollback Configuration
rollback_strategies:
  automatic:
    enabled: true
    triggers:
      - error_rate_spike: "5x baseline"
      - availability_drop: "< 99%"
      - response_time_spike: "3x baseline"
    validation_timeout: "5m"
    
  manual:
    enabled: true
    approval_required: true
    approvers: ["team_lead", "sre_engineer"]
    
  progressive:
    enabled: true
    stages: ["canary", "partial", "full"]
    validation_per_stage: true

# Monitoring and Alerting
monitoring_config:
  metrics_collection:
    interval: "30s"
    retention: "30d"
    
  alerting:
    notification_channels:
      - slack
      - pagerduty
      - email
    
    alert_rules:
      - name: "deployment_failure"
        condition: "deployment_success_rate < 95%"
        severity: "critical"
        
      - name: "high_lead_time"
        condition: "lead_time > 2h"
        severity: "warning"
        
      - name: "frequent_rollbacks"
        condition: "rollback_rate > 10%"
        severity: "warning"

# Environment-Specific Configurations
environments:
  staging:
    deployment_strategy: "rolling"
    quality_gates:
      security: "relaxed"
      performance: "basic"
    rollback:
      automatic: true
      
  production:
    deployment_strategy: "blue_green"
    quality_gates:
      security: "strict"
      performance: "comprehensive"
    rollback:
      automatic: true
      manual_approval: true
      
  development:
    deployment_strategy: "direct"
    quality_gates:
      security: "basic"
      performance: "disabled"
    rollback:
      automatic: false

# Team-Specific Overrides
team_overrides:
  devops:
    deployment_frequency_target: "20/day"
    lead_time_target: "30min"
    canary_traffic_steps: [10, 25, 50, 100]
    
  developer:
    deployment_frequency_target: "10/day"
    lead_time_target: "1h"
    quality_gates:
      code_coverage_min: "80%"
      
  qa:
    deployment_frequency_target: "5/day"
    lead_time_target: "2h"
    quality_gates:
      test_coverage_min: "90%"
      integration_tests: true