---
# Backup Verification and Validation Tasks

- name: Create backup verification directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  loop:
    - "{{ backup_home_dir }}/verification"
    - "{{ backup_home_dir }}/verification/scripts"
    - "{{ backup_home_dir }}/verification/logs"
    - "{{ backup_home_dir }}/verification/checksums"
    - "{{ backup_home_dir }}/verification/manifests"
    - "{{ backup_home_dir }}/verification/reports"
  become: yes
  tags: ['backup-verification', 'directories']

- name: Generate comprehensive backup verification script
  template:
    src: comprehensive-backup-verification.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/comprehensive-backup-verification.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'scripts']

- name: Generate backup checksum verification script
  template:
    src: backup-checksum-verification.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/backup-checksum-verification.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'scripts']

- name: Generate backup manifest validation script
  template:
    src: backup-manifest-validation.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/backup-manifest-validation.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'scripts']

- name: Generate backup consistency checker
  template:
    src: backup-consistency-checker.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/backup-consistency-checker.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'scripts']

- name: Generate backup file integrity scanner
  template:
    src: backup-file-integrity-scanner.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/backup-file-integrity-scanner.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'scripts']

- name: Generate backup repository health checker
  template:
    src: backup-repo-health-checker.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/backup-repo-health-checker.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'scripts']

- name: Generate backup retention policy validator
  template:
    src: backup-retention-validator.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/backup-retention-validator.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'scripts']

- name: Generate backup security compliance checker
  template:
    src: backup-security-compliance.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/backup-security-compliance.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'scripts']

- name: Generate backup verification automation orchestrator
  template:
    src: backup-verification-orchestrator.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/backup-verification-orchestrator.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'scripts']

- name: Create backup verification configuration
  template:
    src: backup-verification-config.yml.j2
    dest: "{{ backup_home_dir }}/verification/backup-verification-config.yml"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0644'
  tags: ['backup-verification', 'config']

- name: Create backup verification systemd service
  template:
    src: backup-verification.service.j2
    dest: /etc/systemd/system/jenkins-backup-verification.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  tags: ['backup-verification', 'systemd']

- name: Create backup verification timer
  template:
    src: backup-verification.timer.j2
    dest: /etc/systemd/system/jenkins-backup-verification.timer
    owner: root
    group: root
    mode: '0644'
  become: yes
  tags: ['backup-verification', 'systemd']

- name: Reload systemd for backup verification services
  systemd:
    daemon_reload: yes
  become: yes
  tags: ['backup-verification', 'systemd']

- name: Enable backup verification timer
  systemd:
    name: jenkins-backup-verification.timer
    enabled: yes
    state: started
  become: yes
  when: backup_verification_automated | default(true)
  tags: ['backup-verification', 'systemd']

- name: Create backup verification metrics collection script
  template:
    src: backup-verification-metrics.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/backup-verification-metrics.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'metrics']

- name: Create backup verification alert configuration
  template:
    src: backup-verification-alerts.yml.j2
    dest: /etc/prometheus/rules/backup-verification-alerts.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  become: yes
  when: prometheus_enabled | default(true)
  notify: reload prometheus
  tags: ['backup-verification', 'monitoring']

- name: Create backup verification dashboard
  template:
    src: backup-verification-dashboard.json.j2
    dest: /var/lib/grafana/dashboards/backup-verification-dashboard.json
    owner: grafana
    group: grafana
    mode: '0644'
  become: yes
  when: grafana_enabled | default(true)
  tags: ['backup-verification', 'monitoring']

- name: Setup backup verification log rotation
  template:
    src: backup-verification-logrotate.j2
    dest: /etc/logrotate.d/jenkins-backup-verification
    owner: root
    group: root
    mode: '0644'
  become: yes
  tags: ['backup-verification', 'logging']

- name: Create backup verification notification script
  template:
    src: backup-verification-notification.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/backup-verification-notification.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'notification']

- name: Create backup verification audit trail script
  template:
    src: backup-verification-audit.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/backup-verification-audit.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'audit']

- name: Generate backup verification SLA checker
  template:
    src: backup-verification-sla.sh.j2
    dest: "{{ backup_home_dir }}/verification/scripts/backup-verification-sla.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0755'
  tags: ['backup-verification', 'sla']

- name: Run initial backup verification
  command: "{{ backup_home_dir }}/verification/scripts/comprehensive-backup-verification.sh --quick-verify"
  register: backup_verification_result
  when: backup_run_initial_verification | default(true)
  failed_when: false
  tags: ['backup-verification', 'initial-verification']

- name: Run backup consistency check
  command: "{{ backup_home_dir }}/verification/scripts/backup-consistency-checker.sh --basic-check"
  register: backup_consistency_result
  when: backup_run_initial_verification | default(true)
  failed_when: false
  tags: ['backup-verification', 'initial-verification']

- name: Run backup security compliance check
  command: "{{ backup_home_dir }}/verification/scripts/backup-security-compliance.sh --audit"
  register: backup_security_compliance_result
  when: 
    - backup_run_initial_verification | default(true)
    - backup_security_compliance_enabled | default(true)
  failed_when: false
  tags: ['backup-verification', 'initial-verification']

- name: Generate backup verification baseline
  template:
    src: backup-verification-baseline.yml.j2
    dest: "{{ backup_home_dir }}/verification/backup-verification-baseline.yml"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0644'
  tags: ['backup-verification', 'baseline']

- name: Create backup verification compliance report
  template:
    src: backup-verification-compliance-report.html.j2
    dest: "{{ backup_home_dir }}/verification/reports/backup-verification-compliance-report.html"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: '0644'
  tags: ['backup-verification', 'compliance']

- name: Display backup verification configuration
  debug:
    msg: |
      Backup Verification Configuration:
      
      Automated Verification: {{ 'Enabled' if backup_verification_automated | default(true) else 'Disabled' }}
      Verification Schedule: {{ backup_verification_schedule | default('0 5 * * *') }} (Daily)
      
      Verification Components:
      - Checksum Validation: Enabled
      - Manifest Validation: Enabled
      - Consistency Checking: Enabled
      - File Integrity Scanning: Enabled
      - Repository Health Checking: Enabled
      - Retention Policy Validation: Enabled
      - Security Compliance: {{ 'Enabled' if backup_security_compliance_enabled | default(true) else 'Disabled' }}
      
      Initial Verification Results:
      - Comprehensive Verification: {{ 'PASSED' if backup_verification_result.rc == 0 else 'FAILED' if backup_verification_result is defined else 'Not Run' }}
      - Consistency Check: {{ 'PASSED' if backup_consistency_result.rc == 0 else 'FAILED' if backup_consistency_result is defined else 'Not Run' }}
      - Security Compliance: {{ 'PASSED' if backup_security_compliance_result.rc == 0 else 'FAILED' if backup_security_compliance_result is defined else 'Not Run' }}
      
      SLA Monitoring: {{ 'Enabled' if backup_sla_monitoring_enabled | default(true) else 'Disabled' }}
      Audit Trail: {{ 'Enabled' if backup_audit_trail_enabled | default(true) else 'Disabled' }}
      
      Management Commands:
      - Run Full Verification: {{ backup_home_dir }}/verification/scripts/backup-verification-orchestrator.sh
      - Check SLA Compliance: {{ backup_home_dir }}/verification/scripts/backup-verification-sla.sh
      - Generate Audit Report: {{ backup_home_dir }}/verification/scripts/backup-verification-audit.sh --report
  tags: ['backup-verification', 'info']