---
# Default variables for common role

# System configuration
common_timezone: "UTC"
common_locale: "en_US.UTF-8"
common_update_packages: true
common_install_tools: true

# Essential packages
common_packages:
  - curl
  - wget
  - git
  - unzip
  - tar
  - vim
  - htop
  - rsync
  - jq
  - python3
  - python3-pip

# SSH configuration
common_ssh_port: 22
common_ssh_permit_root_login: "no"
common_ssh_password_authentication: "no"
common_ssh_max_auth_tries: 3

# Firewall settings
common_firewall_enabled: true
common_firewall_allowed_ports:
  - "22/tcp"  # SSH
  - "80/tcp"  # HTTP
  - "443/tcp" # HTTPS

# Monitoring user
common_monitoring_user: "monitoring"
common_monitoring_user_home: "/home/monitoring"

# Log management
common_logrotate_enabled: true
common_log_retention_days: 30

# NTP configuration
common_ntp_enabled: true
common_ntp_servers:
  - "0.pool.ntp.org"
  - "1.pool.ntp.org"
  - "2.pool.ntp.org"
  - "3.pool.ntp.org"
