---
# Jenkins Master - Blue-Green Deployment Management

- name: Create blue-green management scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ jenkins_master_home_dir }}/scripts/{{ item.dest }}"
    owner: "{{ jenkins_master_user }}"
    group: "{{ jenkins_master_user }}"
    mode: '0755'
  loop:
    - { src: 'blue-green-switch.sh.j2', dest: 'blue-green-switch-{{ jenkins_master_config.team_name }}.sh' }
    - { src: 'blue-green-healthcheck.sh.j2', dest: 'blue-green-healthcheck-{{ jenkins_master_config.team_name }}.sh' }
    - { src: 'blue-green-monitor.sh.j2', dest: 'blue-green-monitor-{{ jenkins_master_config.team_name }}.sh' }
  tags: ['blue-green', 'scripts']

- name: Create blue-green state tracking file
  template:
    src: blue-green-state.json.j2
    dest: "{{ jenkins_master_home_dir }}/{{ jenkins_master_config.team_name }}/blue-green-state.json"
    owner: "{{ jenkins_master_user }}"
    group: "{{ jenkins_master_user }}"
    mode: '0644'
  tags: ['blue-green', 'state']

# HAProxy configuration is managed by the high-availability role

- name: Verify active environment is running
  uri:
    url: "http://{{ ansible_default_ipv4.address }}:{{ jenkins_master_config.ports.web }}/login"
    method: GET
    status_code: [200, 403]  # 403 is acceptable for initial setup
  register: active_env_check
  retries: 10
  delay: 30
  when: jenkins_master_config.active_environment is defined
  tags: ['blue-green', 'verify']

- name: Display blue-green deployment status
  debug:
    msg: |
      Jenkins Blue-Green Deployment Status for {{ jenkins_master_config.team_name | upper }}:
      
      Team: {{ jenkins_master_config.team_name }}
      Active Environment: {{ jenkins_master_config.active_environment | upper }}
      Web URL: http://{{ ansible_default_ipv4.address }}:{{ jenkins_master_config.ports.web }}
      Agent Port: {{ jenkins_master_config.ports.agent }}
      
      Blue Container: jenkins-{{ jenkins_master_config.team_name }}-blue ({{ 'RUNNING' if jenkins_master_config.active_environment == 'blue' else 'STOPPED' }})
      Green Container: jenkins-{{ jenkins_master_config.team_name }}-green ({{ 'RUNNING' if jenkins_master_config.active_environment == 'green' else 'STOPPED' }})
      
      Container Runtime: {{ jenkins_master_container_runtime }}
      Network: {{ jenkins_master_network_name }}
      Resources: {{ jenkins_master_config.resources.memory }} RAM, {{ jenkins_master_config.resources.cpu }} CPU
      
      Management Scripts:
      - Switch Environment: {{ jenkins_master_home_dir }}/scripts/blue-green-switch-{{ jenkins_master_config.team_name }}.sh
      - Health Check: {{ jenkins_master_home_dir }}/scripts/blue-green-healthcheck-{{ jenkins_master_config.team_name }}.sh
      - Monitor: {{ jenkins_master_home_dir }}/scripts/blue-green-monitor-{{ jenkins_master_config.team_name }}.sh
  tags: ['blue-green', 'info']