---
# Jenkins Master - Configuration and Directory Setup

- name: Create Jenkins system user and group
  group:
    name: "{{ jenkins_master_user }}"
    gid: "{{ jenkins_master_gid }}"
    state: present
  become: yes
  tags: ['config', 'user']

- name: Create Jenkins system user
  user:
    name: "{{ jenkins_master_user }}"
    uid: "{{ jenkins_master_uid }}"
    group: "{{ jenkins_master_user }}"
    home: "{{ jenkins_master_home_dir }}"
    shell: /bin/bash
    system: yes
    create_home: yes
  become: yes
  tags: ['config', 'user']

- name: Create team-specific Jenkins directories
  file:
    path: "{{ jenkins_master_home_dir }}/{{ jenkins_master_config.team_name }}"
    state: directory
    owner: "{{ jenkins_master_user }}"
    group: "{{ jenkins_master_user }}"
    mode: '0755'
    recurse: yes
  tags: ['config', 'directories']

- name: Create blue-green environment directories
  file:
    path: "{{ jenkins_master_home_dir }}/{{ jenkins_master_config.team_name }}/{{ item }}"
    state: directory
    owner: "{{ jenkins_master_user }}"
    group: "{{ jenkins_master_user }}"
    mode: '0755'
    recurse: yes
  loop: ['blue', 'green']
  tags: ['config', 'directories', 'blue-green']

- name: Create Jenkins scripts directory
  file:
    path: "{{ jenkins_master_home_dir }}/scripts"
    state: directory
    owner: "{{ jenkins_master_user }}"
    group: "{{ jenkins_master_user }}"
    mode: '0755'
  tags: ['config', 'directories', 'scripts']

- name: Create Jenkins Configuration as Code directory
  file:
    path: "{{ jenkins_master_home_dir }}/{{ jenkins_master_config.team_name }}/{{ item }}/casc_configs"
    state: directory
    owner: "{{ jenkins_master_user }}"
    group: "{{ jenkins_master_user }}"
    mode: '0755'
  loop: ['blue', 'green']
  tags: ['config', 'directories', 'jcasc']

- name: Generate Jenkins Configuration as Code files
  template:
    src: jcasc/jenkins-config.yml.j2
    dest: "{{ jenkins_master_home_dir }}/{{ jenkins_master_config.team_name }}/{{ item }}/casc_configs/jenkins.yaml"
    owner: "{{ jenkins_master_user }}"
    group: "{{ jenkins_master_user }}"
    mode: '0644'
  loop: ['blue', 'green']
  tags: ['config', 'jcasc']