---
# HAProxy High Availability Role - Event Handlers

- name: restart haproxy container
  community.docker.docker_container:
    name: "jenkins-haproxy"
    state: started
    restart: yes
  become: yes
  listen: "restart haproxy container"

- name: restart haproxy
  community.docker.docker_container:
    name: "jenkins-haproxy"
    state: started
    restart: yes
  become: yes
  listen: "restart haproxy"

- name: reload haproxy
  shell: docker exec jenkins-haproxy kill -HUP 1
  become: yes
  listen: "reload haproxy"

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes
  listen: "restart keepalived"

- name: validate haproxy config
  shell: docker exec jenkins-haproxy haproxy -f /usr/local/etc/haproxy/haproxy.cfg -c
  become: yes
  listen: "validate haproxy config"

- name: reload ssl certificates
  community.docker.docker_container:
    name: "jenkins-haproxy"
    state: started
    restart: yes
  become: yes
  listen: "reload ssl certificates"

- name: update haproxy stats
  uri:
    url: "http://{{ ansible_default_ipv4.address }}:{{ haproxy_stats_port | default(8404) }}/stats"
    method: GET
    status_code: 200
  ignore_errors: yes
  listen: "update haproxy stats"