---
# Handlers for high-availability role

- name: restart haproxy
  docker_compose:
    project_src: /etc/haproxy
    state: present
    recreate: always
  become: yes
  listen: "restart haproxy"

- name: restart haproxy container
  systemd:
    name: jenkins-haproxy.service
    state: restarted
    daemon_reload: yes
  become: yes
  listen: "restart haproxy container"

- name: reload haproxy
  docker_container:
    name: jenkins-haproxy
    restart: yes
  become: yes
  listen: "reload haproxy"

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes
  listen: "restart keepalived"

- name: validate haproxy config
  command: docker exec jenkins-haproxy haproxy -f /usr/local/etc/haproxy/haproxy.cfg -c
  become: yes
  listen: "validate haproxy config"

- name: reload ssl certificates
  shell: |
    # Reload HAProxy container to pick up new certificates
    cd /etc/haproxy && docker-compose restart haproxy
  become: yes
  listen: "reload ssl certificates"

- name: update haproxy stats
  uri:
    url: "http://{{ ansible_default_ipv4.address }}:{{ haproxy_stats_port | default(8404) }}/stats"
    method: GET
    status_code: 200
  ignore_errors: yes
  listen: "update haproxy stats"
