---
# Handlers for high-availability role
- name: restart high-availability service
  systemd:
    name: high-availability
    state: restarted
    enabled: yes
  listen: "restart high-availability"

- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
  listen: "restart haproxy"

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
    enabled: yes
  listen: "restart keepalived"
