---
# Unified Jenkins Master - Docker Volume Management
# Supports both single-team and multi-team deployments

- name: Create Jenkins volumes for blue-green environments (Docker)
  community.docker.docker_volume:
    name: "jenkins-{{ item.0.team_name }}-{{ item.1 }}-home"
    driver: "local"
    state: present
    labels:
      team: "{{ item.0.team_name }}"
      environment: "{{ item.1 }}"
      managed_by: "ansible"
  with_nested:
    - "{{ jenkins_effective_config }}"
    - ['blue', 'green']
  loop_control:
    label: "jenkins-{{ item.0.team_name }}-{{ item.1 }}-home"
  tags: ['volumes', 'docker']

- name: Create Jenkins shared volumes for teams (Docker)
  community.docker.docker_volume:
    name: "jenkins-{{ item.team_name }}-shared"
    driver: "local"
    state: present
    labels:
      team: "{{ item.team_name }}"
      type: "shared"
      managed_by: "ansible"
  loop: "{{ jenkins_effective_config }}"
  loop_control:
    label: "jenkins-{{ item.team_name }}-shared"
  tags: ['volumes', 'docker']