---
# Handlers for docker role
- name: restart docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes
  listen: "restart docker"

- name: restart auditd
  systemd:
    name: auditd
    state: restarted
    enabled: yes
  listen: "restart auditd"
