---
# High Availability setup playbook
- name: Configure Jenkins High Availability
  hosts: jenkins_masters
  become: yes
  gather_facts: yes
  serial: 1  # Configure masters one at a time
  
  vars:
    jenkins_ha_enabled: "{{ groups['jenkins_masters'] | length > 1 }}"
    jenkins_master_priority: "{{ play_hosts.index(inventory_hostname) + 1 }}"
    is_primary_master: "{{ inventory_hostname == groups['jenkins_masters'][0] }}"
    
  pre_tasks:
    - name: Verify HA prerequisites
      assert:
        that:
          - groups['jenkins_masters'] | length > 1
          - jenkins_vip is defined
          - shared_storage_path is defined
        fail_msg: "HA setup requires multiple masters, VIP, and shared storage"
        
  roles:
    - role: shared-storage
      tags: ['storage', 'ha']
      when: is_primary_master
      
    - role: high-availability
      tags: ['ha', 'cluster']
      
  tasks:
    - name: Configure shared Jenkins home
      file:
        path: "{{ shared_storage_path }}/jenkins_home"
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'
      when: is_primary_master
      
    - name: Mount shared storage for Jenkins
      mount:
        path: /var/lib/jenkins
        src: "{{ shared_storage_path }}/jenkins_home"
        fstype: nfs
        opts: defaults,_netdev
        state: mounted
      when: shared_storage_type == 'nfs'
      
    - name: Configure Jenkins for HA mode
      lineinfile:
        path: /etc/default/jenkins
        regexp: '^JENKINS_ARGS='
        line: 'JENKINS_ARGS="--webroot=/var/cache/jenkins/war --httpPort=8080 --httpListenAddress=0.0.0.0"'
        backup: yes
      notify: restart jenkins
      
    - name: Wait for Jenkins to be operational
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:8080/login"
        method: GET
        status_code: [200, 403]
      register: jenkins_ready
      until: jenkins_ready is succeeded
      retries: 30
      delay: 10
      
  post_tasks:
    - name: Verify HA cluster status
      uri:
        url: "http://{{ jenkins_vip }}:8080/api/json"
        method: GET
      register: ha_status
      run_once: true
      
    - name: Display HA setup results
      debug:
        msg: |
          HA Setup completed:
          - Primary Master: {{ groups['jenkins_masters'][0] }}
          - Secondary Masters: {{ groups['jenkins_masters'][1:] | join(', ') }}
          - Virtual IP: {{ jenkins_vip }}
          - Shared Storage: {{ shared_storage_path }}
      run_once: true
