---
# Simplified HAProxy HA Monitoring - VIP Management and Health Monitoring
# Consolidates: main.yml VIP parts + management scripts + monitoring setup
# Reduces management and monitoring complexity while maintaining enterprise features

# ====================================
# VIP MANAGEMENT (KEEPALIVED)
# ====================================

- name: Configure Virtual IP management with keepalived
  block:
    - name: Install keepalived package
      package:
        name: keepalived
        state: present
      become: yes

    - name: Create keepalived configuration directory
      file:
        path: /etc/keepalived
        state: directory
        mode: '0755'
      become: yes

    - name: Generate keepalived configuration for VIP
      template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        backup: yes
        owner: root
        group: root
        mode: '0644'
      become: yes
      notify: restart keepalived
      register: keepalived_config

    - name: Validate keepalived configuration
      command: keepalived -t -f /etc/keepalived/keepalived.conf
      register: keepalived_validation
      failed_when: keepalived_validation.rc != 0
      changed_when: false
      become: yes

    - name: Start and enable keepalived service
      systemd:
        name: keepalived
        state: started
        enabled: yes
        daemon_reload: yes
      become: yes

    - name: Verify VIP assignment (master node)
      command: ip addr show
      register: vip_check
      changed_when: false
      when: keepalived_priority | default(100) > 100

    - name: Display VIP status
      debug:
        msg: |
          VIP Configuration:
          IP: {{ jenkins_vip }}
          Priority: {{ keepalived_priority | default(100) }}
          State: {{ 'MASTER' if keepalived_priority | default(100) > 100 else 'BACKUP' }}
          {% if keepalived_priority | default(100) > 100 %}
          VIP Assigned: {{ 'Yes' if jenkins_vip in vip_check.stdout else 'No' }}
          {% endif %}
  when: jenkins_vip is defined and jenkins_vip != ""
  tags: ['vip', 'keepalived']

# ====================================
# MANAGEMENT SCRIPTS DEPLOYMENT
# ====================================

- name: Deploy HAProxy management and monitoring scripts
  block:
    - name: Create management scripts from templates
      template:
        src: "{{ item }}.j2"
        dest: "/usr/local/bin/{{ item }}"
        mode: '0755'
        owner: root
        group: root
      loop:
        - jenkins-ha-monitor.sh
        - jenkins-failover.sh
        - haproxy-container-manager.sh
        - keepalived-haproxy-check.sh
      become: yes
      register: management_scripts

    - name: Verify management scripts are executable
      file:
        path: "/usr/local/bin/{{ item }}"
        mode: '0755'
        state: file
      loop:
        - jenkins-ha-monitor.sh
        - jenkins-failover.sh
        - haproxy-container-manager.sh
        - keepalived-haproxy-check.sh
      become: yes

    - name: Test management scripts syntax
      command: "bash -n /usr/local/bin/{{ item }}"
      loop:
        - jenkins-ha-monitor.sh
        - jenkins-failover.sh
        - haproxy-container-manager.sh
        - keepalived-haproxy-check.sh
      register: script_syntax_check
      failed_when: script_syntax_check.rc != 0
      changed_when: false
      become: yes
  tags: ['scripts', 'management']

# ====================================
# HEALTH MONITORING CONFIGURATION
# ====================================

- name: Configure HAProxy health monitoring
  block:
    - name: Check if crontab is available
      command: which crontab
      register: crontab_check
      failed_when: false
      changed_when: false

    - name: Setup automated HA monitoring cron job
      cron:
        name: "Jenkins HA Health Monitoring"
        job: "/usr/local/bin/jenkins-ha-monitor.sh >> /var/log/jenkins-ha-monitor.log 2>&1"
        minute: "*/2"
        user: root
        state: present
      become: yes
      when: crontab_check.rc == 0

    - name: Create log rotation for HA monitoring
      copy:
        dest: /etc/logrotate.d/jenkins-ha-monitor
        content: |
          /var/log/jenkins-ha-monitor.log {
              daily
              missingok
              rotate 7
              compress
              notifempty
              create 644 root root
          }
        mode: '0644'
      become: yes
      when: crontab_check.rc == 0

    - name: Skip cron job setup notification (development environments)
      debug:
        msg: "Skipping HA monitoring cron job - crontab not installed (development environment)"
      when: crontab_check.rc != 0

    - name: Create monitoring status directory
      file:
        path: /var/lib/jenkins-ha
        state: directory
        mode: '0755'
        owner: root
        group: root
      become: yes

    - name: Initialize HA monitoring state file
      copy:
        dest: /var/lib/jenkins-ha/status.json
        content: |
          {
            "last_check": "{{ ansible_date_time.iso8601 }}",
            "haproxy_status": "unknown",
            "vip_status": "{{ 'enabled' if jenkins_vip is defined and jenkins_vip != '' else 'disabled' }}",
            "teams_configured": {{ haproxy_effective_teams | length }},
            "deployment_mode": "{{ haproxy_deployment_mode }}"
          }
        mode: '0644'
        force: no
      become: yes
  tags: ['monitoring', 'health']

# ====================================
# COMPREHENSIVE HEALTH VERIFICATION
# ====================================

- name: Perform comprehensive HA health verification
  block:
    - name: Execute initial health check
      command: /usr/local/bin/jenkins-ha-monitor.sh
      register: initial_health_check
      failed_when: false
      changed_when: false
      become: yes

    - name: Test HAProxy container management script
      command: /usr/local/bin/haproxy-container-manager.sh status
      register: container_mgmt_test
      failed_when: false
      changed_when: false
      become: yes

    - name: Test VIP check script (if VIP enabled)
      command: /usr/local/bin/keepalived-haproxy-check.sh
      register: vip_check_test
      failed_when: false
      changed_when: false
      become: yes
      when: jenkins_vip is defined and jenkins_vip != ""

    - name: Verify HAProxy stats accessibility
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:{{ haproxy_stats_port | default(8404) }}{{ haproxy_stats_uri | default('/stats') }}"
        method: GET
        timeout: 10
        user: "{{ haproxy_stats_user | default('admin') }}"
        password: "{{ haproxy_stats_password | default('admin123') }}"
        force_basic_auth: true
        status_code: [200, 401]  # Accept both authenticated access and auth prompts
      register: stats_accessibility
      retries: 3
      delay: 5
      failed_when: false  # Don't fail on authentication issues, just report status

    - name: Test team-specific routing functionality
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:8090"
        method: HEAD
        timeout: 10
        headers:
          Host: "{{ item.team_name }}.{{ jenkins_domain | default('devops.example.com') }}"
      loop: "{{ haproxy_effective_teams }}"
      loop_control:
        label: "{{ item.team_name }}.{{ jenkins_domain }}"
      register: team_routing_test
      retries: 2
      delay: 3
      failed_when: false  # Don't fail on routing tests
      when: haproxy_effective_teams | length > 0

    - name: Display comprehensive HA status verification
      debug:
        msg: |
          ======================================================
          HAProxy High Availability Status Verification
          ======================================================
          
          🐳 Container Status:
          HAProxy Container: {{ 'Running' if container_mgmt_test.rc == 0 else 'Issues detected' }}
          
          📊 Monitoring Status:
          Health Check Script: {{ 'Functional' if initial_health_check.rc == 0 else 'Issues detected' }}
          Stats Endpoint: {{ 'Accessible' if stats_accessibility.status == 200 else 'Not accessible' }}
          Monitoring Cron: {{ 'Configured' if crontab_check.rc == 0 else 'Skipped (no crontab)' }}
          
          {% if jenkins_vip is defined and jenkins_vip != "" %}
          🎯 VIP Management:
          VIP Address: {{ jenkins_vip }}
          VIP Priority: {{ keepalived_priority | default(100) }}
          VIP Check Script: {{ 'Functional' if vip_check_test.rc == 0 else 'Issues detected' }}
          Keepalived Status: {{ 'Active' if keepalived_validation.rc == 0 else 'Configuration issues' }}
          {% endif %}
          
          👥 Team Routing:
          {% if haproxy_effective_teams | length > 0 %}
          {% for result in team_routing_test.results %}
          • {{ haproxy_effective_teams[loop.index0].team_name }}: {{ 'OK' if result.status | default(0) in [200, 302, 404, 503] else 'Failed' }}
          {% endfor %}
          {% else %}
          Single-team configuration (no team-specific routing)
          {% endif %}
          
          📁 Management Scripts:
          {% for script in ['jenkins-ha-monitor.sh', 'jenkins-failover.sh', 'haproxy-container-manager.sh', 'keepalived-haproxy-check.sh'] %}
          • {{ script }}: Available at /usr/local/bin/{{ script }}
          {% endfor %}
          
          ======================================================
  tags: ['verify', 'health']

- name: HA monitoring and VIP management phase complete
  debug:
    msg: |
      ====================================
      HA Monitoring Setup Complete
      ====================================
      Management Scripts: 4 deployed
      Health Monitoring: {{ 'Automated' if crontab_check.rc == 0 else 'Manual only' }}
      {% if jenkins_vip is defined and jenkins_vip != "" %}
      VIP Management: {{ jenkins_vip }} (keepalived)
      {% endif %}
      Status Verification: Complete
      ====================================
  tags: ['monitoring']