---
# Jenkins Infrastructure - Dynamic Agent Configuration Tasks
# This file previously contained static agent configurations
# Now focuses solely on dynamic agent setup and support

- name: Create Jenkins dynamic agent configuration directories
  file:
    path: "{{ jenkins_home_dir }}/dynamic-agents/{{ item }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
    recurse: yes
  loop:
    - "templates"
    - "configs"
    - "logs"
  tags: ['agents', 'directories', 'dynamic']

- name: Create dynamic agent workspace directories in shared storage
  file:
    path: "{{ shared_storage_path | default('/shared/jenkins') }}/dynamic-workspaces"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
    recurse: yes
  tags: ['agents', 'workspace', 'dynamic']

- name: Create Docker cache volumes for dynamic agents
  docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - "jenkins-dynamic-maven-cache"
    - "jenkins-dynamic-python-cache"
    - "jenkins-dynamic-nodejs-cache"
    - "jenkins-dynamic-docker-cache"
  when: jenkins_container_runtime == 'docker'
  tags: ['agents', 'volumes', 'dynamic', 'docker']

- name: Create Podman volumes for dynamic agents
  containers.podman.podman_volume:
    name: "{{ item }}"
    state: present
  loop:
    - "jenkins-dynamic-maven-cache"
    - "jenkins-dynamic-python-cache"
    - "jenkins-dynamic-nodejs-cache"
    - "jenkins-dynamic-docker-cache"
  when: jenkins_container_runtime == 'podman'
  tags: ['agents', 'volumes', 'dynamic', 'podman']

- name: Setup dynamic agent log rotation
  template:
    src: jenkins-dynamic-agent-logrotate.j2
    dest: /etc/logrotate.d/jenkins-dynamic-agents
    mode: '0644'
  tags: ['agents', 'logging', 'dynamic']

- name: Create dynamic agent monitoring script
  template:
    src: jenkins-dynamic-agent-monitor.sh.j2
    dest: "{{ jenkins_home_dir }}/bin/jenkins-dynamic-agent-monitor.sh"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
  tags: ['agents', 'monitoring', 'dynamic']

- name: Display dynamic agent configuration status
  debug:
    msg: |
      Dynamic Jenkins Agent Configuration Completed:
      
      Dynamic Agent Support: Enabled
      Container Runtime: {{ jenkins_container_runtime }}
      Network: {{ jenkins_network_name }}
      Shared Storage: {{ shared_storage_path | default('/shared/jenkins') }}
      
      Dynamic Agent Types Available:
      - DIND Agent: For Docker-in-Docker builds (privileged)
      - Maven Agent: For Java/Maven builds
      - Python Agent: For Python development
      - Node.js Agent: For Node.js/frontend development
      
      Cache Volumes Created:
      - Maven cache: jenkins-dynamic-maven-cache
      - Python cache: jenkins-dynamic-python-cache  
      - Node.js cache: jenkins-dynamic-nodejs-cache
      - Docker cache: jenkins-dynamic-docker-cache
      
      Agent Provisioning: Via Docker Cloud Plugin in JCasC
      Log Rotation: Configured for /var/log/jenkins/dynamic-agents.log
      Monitoring: {{ jenkins_home_dir }}/bin/jenkins-dynamic-agent-monitor.sh
  tags: ['agents', 'info', 'dynamic']