---
# Jenkins Blue-Green Management Scripts Deployment
# Creates and configures all management scripts for blue-green deployment

- name: Create blue-green scripts directory
  file:
    path: "{{ jenkins_home_dir }}/blue-green/scripts"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
  tags: ['blue-green', 'scripts', 'directories']

- name: Create logs directory for blue-green operations
  file:
    path: "{{ jenkins_home_dir }}/blue-green/logs"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
  tags: ['blue-green', 'scripts', 'directories']

- name: Deploy blue-green environment switch script
  template:
    src: blue-green-switch.sh.j2
    dest: "{{ jenkins_home_dir }}/blue-green/scripts/switch-environment.sh"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
    backup: yes
  tags: ['blue-green', 'scripts', 'switch']

- name: Deploy blue-green health check script
  template:
    src: blue-green-health-check.sh.j2
    dest: "{{ jenkins_home_dir }}/blue-green/scripts/health-check.sh"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
    backup: yes
  tags: ['blue-green', 'scripts', 'health']

- name: Deploy blue-green rollback script
  template:
    src: blue-green-rollback.sh.j2
    dest: "{{ jenkins_home_dir }}/blue-green/scripts/rollback.sh"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
    backup: yes
  tags: ['blue-green', 'scripts', 'rollback']

- name: Deploy blue-green backup script
  template:
    src: blue-green-backup.sh.j2
    dest: "{{ jenkins_home_dir }}/blue-green/scripts/backup.sh"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
    backup: yes
  tags: ['blue-green', 'scripts', 'backup']

- name: Deploy blue-green management wrapper script
  template:
    src: blue-green-manager.sh.j2
    dest: "{{ jenkins_home_dir }}/blue-green/scripts/manager.sh"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
    backup: yes
  tags: ['blue-green', 'scripts', 'manager']

- name: Create system-wide symlinks for blue-green scripts
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: root
    group: root
    force: yes
  loop:
    - src: "{{ jenkins_home_dir }}/blue-green/scripts/switch-environment.sh"
      dest: "/usr/local/bin/jenkins-bg-switch"
    - src: "{{ jenkins_home_dir }}/blue-green/scripts/health-check.sh"
      dest: "/usr/local/bin/jenkins-bg-health"
    - src: "{{ jenkins_home_dir }}/blue-green/scripts/rollback.sh"
      dest: "/usr/local/bin/jenkins-bg-rollback"
    - src: "{{ jenkins_home_dir }}/blue-green/scripts/backup.sh"
      dest: "/usr/local/bin/jenkins-bg-backup"
    - src: "{{ jenkins_home_dir }}/blue-green/scripts/manager.sh"
      dest: "/usr/local/bin/jenkins-bg"
  become: yes
  tags: ['blue-green', 'scripts', 'symlinks']

- name: Create blue-green cron jobs for automated operations
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    user: "{{ jenkins_user }}"
    state: "{{ 'present' if item.enabled | default(false) | bool else 'absent' }}"
  loop:
    - name: "Jenkins Blue-Green Health Check"
      job: "{{ jenkins_home_dir }}/blue-green/scripts/health-check.sh quick >> {{ jenkins_home_dir }}/blue-green/logs/cron-health.log 2>&1"
      minute: "*/15"
      enabled: "{{ jenkins_bg_automated_health_check | default(true) }}"
    - name: "Jenkins Blue-Green Backup"
      job: "{{ jenkins_home_dir }}/blue-green/scripts/backup.sh automated >> {{ jenkins_home_dir }}/blue-green/logs/cron-backup.log 2>&1"
      minute: "0"
      hour: "3"
      enabled: "{{ jenkins_bg_automated_backup | default(false) }}"
    - name: "Jenkins Blue-Green Log Cleanup"
      job: "find {{ jenkins_home_dir }}/blue-green/logs -name '*.json' -mtime +30 -delete"
      minute: "0"
      hour: "4"
      weekday: "0"
      enabled: "{{ jenkins_bg_log_cleanup | default(true) }}"
  tags: ['blue-green', 'scripts', 'cron']

- name: Create blue-green script configuration file
  template:
    src: blue-green-config.sh.j2
    dest: "{{ jenkins_home_dir }}/blue-green/scripts/config.sh"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0644'
    backup: yes
  tags: ['blue-green', 'scripts', 'config']

- name: Create blue-green log rotation configuration
  copy:
    content: |
      {{ jenkins_home_dir }}/blue-green/logs/*.log {
          daily
          rotate 30
          compress
          delaycompress
          missingok
          notifempty
          copytruncate
          su {{ jenkins_user }} {{ jenkins_group }}
          postrotate
              # Optional: Send log rotation notification
              echo "$(date): Blue-Green logs rotated" >> {{ jenkins_home_dir }}/blue-green/logs/rotation.log
          endscript
      }
    dest: /etc/logrotate.d/jenkins-blue-green
    owner: root
    group: root
    mode: '0644'
  become: yes
  tags: ['blue-green', 'scripts', 'logging']

- name: Create blue-green deployment hooks directory
  file:
    path: "{{ jenkins_home_dir }}/blue-green/hooks"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
  tags: ['blue-green', 'scripts', 'hooks']

- name: Deploy blue-green deployment hooks
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
  loop:
    - src: "blue-green-pre-switch-hook.sh.j2"
      dest: "{{ jenkins_home_dir }}/blue-green/hooks/pre-switch.sh"
    - src: "blue-green-post-switch-hook.sh.j2"
      dest: "{{ jenkins_home_dir }}/blue-green/hooks/post-switch.sh"
    - src: "blue-green-rollback-hook.sh.j2"
      dest: "{{ jenkins_home_dir }}/blue-green/hooks/rollback.sh"
  tags: ['blue-green', 'scripts', 'hooks']

- name: Test blue-green scripts functionality
  command: "{{ item.script }} {{ item.args | default('') }}"
  loop:
    - script: "{{ jenkins_home_dir }}/blue-green/scripts/health-check.sh"
      args: "quick"
    - script: "{{ jenkins_home_dir }}/blue-green/scripts/switch-environment.sh"
      args: "status"
  register: script_test_results
  failed_when: false
  changed_when: false
  tags: ['blue-green', 'scripts', 'test']

- name: Display blue-green scripts deployment summary
  debug:
    msg: |
      === Jenkins Blue-Green Scripts Deployed Successfully ===
      
      Management Scripts Location: {{ jenkins_home_dir }}/blue-green/scripts/
      
      Available Scripts:
        Environment Switch: {{ jenkins_home_dir }}/blue-green/scripts/switch-environment.sh
        Health Check: {{ jenkins_home_dir }}/blue-green/scripts/health-check.sh
        Rollback: {{ jenkins_home_dir }}/blue-green/scripts/rollback.sh
        Backup: {{ jenkins_home_dir }}/blue-green/scripts/backup.sh
        Manager: {{ jenkins_home_dir }}/blue-green/scripts/manager.sh
      
      System Commands (via symlinks):
        jenkins-bg           - Main management interface
        jenkins-bg-switch    - Environment switching
        jenkins-bg-health    - Health checking
        jenkins-bg-rollback  - Rollback operations
        jenkins-bg-backup    - Backup operations
      
      Logs Location: {{ jenkins_home_dir }}/blue-green/logs/
      Configuration: {{ jenkins_home_dir }}/blue-green/scripts/config.sh
      Deployment Hooks: {{ jenkins_home_dir }}/blue-green/hooks/
      
      Automated Operations:
        Health Check: {{ 'Every 15 minutes' if jenkins_bg_automated_health_check | default(true) | bool else 'Disabled' }}
        Backup: {{ 'Daily at 3:00 AM' if jenkins_bg_automated_backup | default(false) | bool else 'Disabled' }}
        Log Cleanup: {{ 'Weekly (Sunday 4:00 AM)' if jenkins_bg_log_cleanup | default(true) | bool else 'Disabled' }}
      
      Usage Examples:
        jenkins-bg status                    # Show deployment status
        jenkins-bg switch                    # Switch environments
        jenkins-bg-health                    # Check health
        jenkins-bg-rollback                  # Rollback to previous
        jenkins-bg-backup create             # Create backup
      
      Log Rotation: Configured for 30-day retention
  tags: ['blue-green', 'scripts', 'info']

- name: Create blue-green scripts completion indicator
  file:
    path: "{{ jenkins_home_dir }}/blue-green/.scripts-deployed"
    state: touch
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0644'
  tags: ['blue-green', 'scripts', 'completion']