---
# Jenkins Infrastructure - Network Configuration Tasks

- name: Create Jenkins Docker network
  community.docker.docker_network:
    name: "{{ jenkins_network_name }}"
    driver: "{{ jenkins_network_driver }}"
    ipam_config:
      - subnet: "{{ jenkins_network_subnet }}"
        gateway: "{{ jenkins_network_gateway }}"
    state: present
  when: jenkins_container_runtime == 'docker'
  tags: ['network', 'docker']

- name: Create Jenkins Podman network
  containers.podman.podman_network:
    name: "{{ jenkins_network_name }}"
    subnet: "{{ jenkins_network_subnet }}"
    gateway: "{{ jenkins_network_gateway }}"
    state: present
  when: jenkins_container_runtime == 'podman'
  tags: ['network', 'podman']

- name: Configure firewall rules for Jenkins network
  ansible.posix.firewalld:
    zone: public
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - "{{ jenkins_port }}/tcp"
    - "{{ jenkins_agent_port }}/tcp"
  when: 
    - ansible_os_family == "RedHat"
    - firewalld_service is defined and firewalld_service.state == "running"
  notify: restart firewalld
  tags: ['network', 'firewall']

- name: Configure UFW rules for Jenkins network
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    state: enabled
  loop:
    - "{{ jenkins_port }}"
    - "{{ jenkins_agent_port }}"
  when: 
    - ansible_os_family == "Debian"
    - ufw_service is defined and ufw_service.state == "running"
  tags: ['network', 'firewall']

- name: Create Jenkins network configuration file
  template:
    src: network-config.yml.j2
    dest: "{{ jenkins_home_dir }}/network-config.yml"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0644'
  tags: ['network', 'config']

- name: Verify network connectivity
  command: >
    {% if jenkins_container_runtime == 'docker' %}
    docker network inspect {{ jenkins_network_name }}
    {% else %}
    podman network inspect {{ jenkins_network_name }}
    {% endif %}
  register: network_info
  changed_when: false
  tags: ['network', 'verify']

- name: Display network configuration
  debug:
    msg: |
      Jenkins Network Configuration:
      Name: {{ jenkins_network_name }}
      Subnet: {{ jenkins_network_subnet }}
      Gateway: {{ jenkins_network_gateway }}
      Driver: {{ jenkins_network_driver }}
      Runtime: {{ jenkins_container_runtime }}
  tags: ['network', 'info']