---
# Jenkins Master Role - Reusable Default Variables

# Core Jenkins Configuration
jenkins_master_user: "jenkins"
jenkins_master_gid: 1000
jenkins_master_uid: 1000
jenkins_master_home_dir: "/var/jenkins"
jenkins_master_port: 8080
jenkins_master_agent_port: 50000
jenkins_master_container_home: "/var/jenkins_home"
jenkins_master_shared_path: "/shared/jenkins"

# Container Runtime Configuration
jenkins_master_container_runtime: "podman"  # docker or podman
jenkins_master_restart_policy: "unless-stopped"
jenkins_master_startup_wait_time: 20

# Image Configuration
jenkins_master_image_registry: "{{ harbor_registry_url | default('docker.io') }}"
jenkins_master_image_name: "{{ harbor_project | default('jenkins') }}/jenkins"
jenkins_master_image_tag: "lts"

# Network Configuration
jenkins_master_network_name: "jenkins-network"
jenkins_master_network_driver: "bridge"
jenkins_master_network_subnet: "172.20.0.0/16"
jenkins_master_network_gateway: "172.20.0.1"

# Logging Configuration
jenkins_master_log_driver: "journald"
jenkins_master_log_max_size: "10m"
jenkins_master_log_max_files: "3"

# Default Environment Variables
jenkins_master_env_vars:
  JAVA_OPTS: "-Djenkins.install.runSetupWizard=false -Dhudson.DNSMultiCast.disabled=true"
  JENKINS_OPTS: "--httpPort={{ jenkins_master_port }}"
  CASC_JENKINS_CONFIG: "{{ jenkins_master_container_home }}/casc_configs"
  TZ: "{{ common_timezone | default('UTC') }}"

# Default Labels
jenkins_master_labels:
  service: "jenkins-master"
  managed_by: "ansible"
  role: "jenkins-master"

# Health Check Configuration
jenkins_master_health_check_retries: 30
jenkins_master_health_check_delay: 10
jenkins_master_health_check_timeout: 60

# HAProxy Integration
jenkins_master_haproxy_enabled: true

# Blue-Green Deployment Configuration
jenkins_master_blue_green_enabled: true

# Cleanup Configuration
jenkins_master_cleanup_enabled: false
jenkins_master_cleanup_containers: false
jenkins_master_cleanup_volumes: false
jenkins_master_cleanup_images: false
jenkins_master_cleanup_logs: false
jenkins_master_log_retention_days: 30

# Default Team Configuration Structure (Example)
# Users should override jenkins_master_config in their inventory
jenkins_master_config:
  team_name: "default"
  active_environment: "blue"
  ports:
    web: 8080
    agent: 50000
  resources:
    memory: "2g"
    cpu: "1.0"
  env_vars: {}
  labels: {}

# Security Configuration
jenkins_master_security_enabled: true
jenkins_master_csrf_protection: true
jenkins_master_agent_protocols: ["JNLP4-connect", "Ping"]

# JCasC Configuration
jenkins_master_casc_enabled: true
jenkins_master_casc_config_path: "{{ jenkins_master_container_home }}/casc_configs"

# Dynamic Agent Support
jenkins_master_dynamic_agents_enabled: true
jenkins_master_dynamic_agent_image_tag: "latest"

# Monitoring Integration
jenkins_master_monitoring_enabled: true
jenkins_master_prometheus_metrics: true