---
# Jenkins Master Role - Event Handlers

- name: reload haproxy
  systemd:
    name: haproxy
    state: reloaded
  become: yes
  listen: "reload haproxy"

- name: restart jenkins docker containers
  community.docker.docker_container:
    name: "jenkins-{{ item.team_name }}-{{ item.active_environment }}"
    state: restarted
  loop: "{{ jenkins_effective_config | default([]) }}"
  loop_control:
    label: "jenkins-{{ item.team_name }}-{{ item.active_environment }}"
  when: 
    - jenkins_master_container_runtime == 'docker'
    - jenkins_effective_config is defined
  become: yes
  listen: "restart jenkins"

- name: restart jenkins podman containers
  containers.podman.podman_container:
    name: "jenkins-{{ item.team_name }}-{{ item.active_environment }}"
    state: restarted
  loop: "{{ jenkins_effective_config | default([]) }}"
  loop_control:
    label: "jenkins-{{ item.team_name }}-{{ item.active_environment }}"
  when: 
    - jenkins_master_container_runtime == 'podman'
    - jenkins_effective_config is defined
  become: yes
  listen: "restart jenkins"

- name: update haproxy backend
  template:
    src: haproxy-team-config.cfg.j2
    dest: "/etc/haproxy/conf.d/jenkins-{{ item.team_name }}.cfg"
    owner: root
    group: root
    mode: '0644'
  notify: reload haproxy
  loop: "{{ jenkins_effective_config | default([]) }}"
  loop_control:
    label: "jenkins-{{ item.team_name }}"
  when: jenkins_effective_config is defined
  become: yes
  listen: "update haproxy backend"