---
# Jenkins Master Role - Event Handlers
# Note: HAProxy management is handled by the high-availability role

- name: restart jenkins containers
  community.docker.docker_container:
    name: "jenkins-{{ item.team_name }}-{{ item.active_environment }}"
    state: started
    restart: true
  loop: "{{ jenkins_effective_config | default([]) }}"
  loop_control:
    label: "jenkins-{{ item.team_name }}-{{ item.active_environment }}"
  when: jenkins_effective_config is defined
  become: yes
  listen: "restart jenkins"

# HAProxy backend updates are handled by the high-availability role
# The high-availability role manages the complete HAProxy configuration