---
# Handlers for jenkins-infrastructure role
- name: restart jenkins-infrastructure service
  systemd:
    name: jenkins-infrastructure
    state: restarted
    enabled: yes
  listen: "restart jenkins-infrastructure"

- name: restart jenkins
  systemd:
    name: jenkins
    state: restarted
    enabled: yes
  listen: "restart jenkins"

- name: restart jenkins master containers
  systemd:
    name: "jenkins-master-{{ item }}"
    state: restarted
    enabled: yes
  loop: "{{ range(1, jenkins_master_count + 1) | list }}"
  when: jenkins_systemd_enabled | default(false) | bool
  listen: "restart jenkins master containers"

- name: restart jenkins master containers (docker direct)
  community.docker.docker_container:
    name: "jenkins-master-{{ item }}"
    state: started
    restart: yes
  loop: "{{ range(1, jenkins_master_count + 1) | list }}"
  when: not (jenkins_systemd_enabled | default(false) | bool) and jenkins_container_runtime == 'docker'
  listen: "restart jenkins master containers"

- name: restart jenkins master containers (podman direct)
  containers.podman.podman_container:
    name: "jenkins-master-{{ item }}"
    state: started
    restart: yes
  loop: "{{ range(1, jenkins_master_count + 1) | list }}"
  when: not (jenkins_systemd_enabled | default(false) | bool) and jenkins_container_runtime == 'podman'
  listen: "restart jenkins master containers"

- name: restart jenkins agents
  docker_container:
    name: "{{ item }}"
    state: started
    restart: yes
  with_items: "{{ jenkins_agents | default([]) }}"
  listen: "restart jenkins agents"

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted
    enabled: yes
  listen: "restart firewalld"

- name: reload systemd
  systemd:
    daemon_reload: yes
  listen: "reload systemd"
