---
# Default variables for security role

# General Security Configuration
security_enabled: true
security_hardening_enabled: true
security_scanning_enabled: true
jenkins_security_enabled: true

# SSL/TLS Configuration
ssl_enabled: false
ssl_force_regenerate: false
ssl_auto_renewal_enabled: true
ssl_backup_enabled: true
ssl_use_letsencrypt: false
letsencrypt_auto_renewal_enabled: true

# SSL Certificate Directories
ssl_certificate_dir: "/etc/ssl/certs"
ssl_private_key_dir: "/etc/ssl/private"
ssl_ca_dir: "/etc/ssl/ca"
ssl_csr_dir: "/etc/ssl/csr"
ssl_backup_dir: "/backup/ssl"

# SSL Certificate Authority
ssl_ca_common_name: "Jenkins HA CA"
ssl_ca_private_key_path: "{{ ssl_ca_dir }}/ca-key.pem"
ssl_ca_certificate_path: "{{ ssl_ca_dir }}/ca-cert.pem"
ssl_ca_csr_path: "{{ ssl_csr_dir }}/ca.csr"
ssl_ca_validity_days: 3650  # 10 years

# SSL Certificate Configuration
ssl_default_validity_days: 365
ssl_renewal_threshold_days: 30
ssl_generate_dh_params: true
ssl_dh_params_path: "/etc/ssl/dhparam.pem"
vault_ca_key_password: ""

# SSL Services Configuration
ssl_services:
  - name: "jenkins-master"
    common_name: "{{ jenkins_vip | default('jenkins.company.local') }}"
    san:
      - "DNS:{{ jenkins_vip | default('jenkins.company.local') }}"
      - "DNS:jenkins-master-01.company.local"
      - "DNS:jenkins-master-02.company.local"
      - "IP:{{ vault_jenkins_vip | default('10.0.1.100') }}"
    owner: "jenkins"
    group: "jenkins"
    cert_dest_path: "/var/lib/jenkins/jenkins.crt"
    key_dest_path: "/var/lib/jenkins/jenkins.key"
    bundle_dest_path: "/var/lib/jenkins/jenkins-bundle.crt"
    validity_days: 365
    use_letsencrypt: false
  
  
  - name: "grafana"
    common_name: "{{ monitoring_hostname | default('monitoring.company.local') }}"
    san:
      - "DNS:{{ monitoring_hostname | default('monitoring.company.local') }}"
      - "DNS:monitoring-01.company.local"
      - "IP:{{ vault_monitoring_vip | default('10.0.1.101') }}"
    owner: "grafana"
    group: "grafana"
    cert_dest_path: "/etc/grafana/ssl/grafana.crt"
    key_dest_path: "/etc/grafana/ssl/grafana.key"
    bundle_dest_path: "/etc/grafana/ssl/grafana-bundle.crt"
    validity_days: 365
    use_letsencrypt: false
  
  - name: "prometheus"
    common_name: "{{ monitoring_hostname | default('monitoring.company.local') }}"
    san:
      - "DNS:{{ monitoring_hostname | default('monitoring.company.local') }}"
      - "DNS:monitoring-01.company.local"
      - "IP:{{ vault_monitoring_vip | default('10.0.1.101') }}"
    owner: "prometheus"
    group: "prometheus"
    cert_dest_path: "/etc/prometheus/ssl/prometheus.crt"
    key_dest_path: "/etc/prometheus/ssl/prometheus.key"
    bundle_dest_path: "/etc/prometheus/ssl/prometheus-bundle.crt"
    validity_days: 365
    use_letsencrypt: false

# SSL Security Hardening
ssl_ocsp_stapling_enabled: true
ssl_ct_monitoring_enabled: false
ssl_vulnerability_scanning_enabled: true
ssl_certificate_pinning_enabled: false
ssl_revocation_checking_enabled: true
nginx_ssl_hardening_enabled: true
apache_ssl_hardening_enabled: false
fail2ban_ssl_protection_enabled: true

# Java Keystore Configuration
java_keystore_path: "/usr/lib/jvm/default-java/lib/security/cacerts"
java_keystore_password: "changeit"

# Firewall Configuration
# Note: firewall_allowed_ports should be defined in inventory with protocol (e.g., "22/tcp")
# Example:
# firewall_allowed_ports:
#   - "22/tcp"    # SSH
#   - "80/tcp"    # HTTP
#   - "443/tcp"   # HTTPS

# SSH Hardening - Basic system access only (not used for Jenkins agents)
ssh_hardening_enabled: false  # Disabled as Jenkins no longer uses SSH for agents
ssh_port: 22
ssh_permit_root_login: false
ssh_password_authentication: false
ssh_pubkey_authentication: true
ssh_max_auth_tries: 3
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2

# Fail2ban Configuration
fail2ban_enabled: true
fail2ban_jail_configs:
  - name: "sshd"
    enabled: true
    port: "ssh"
    filter: "sshd"
    logpath: "/var/log/auth.log"
    maxretry: 3
    findtime: 600
    bantime: 3600
  - name: "jenkins"
    enabled: true
    port: "8080,8081"
    filter: "jenkins"
    logpath: "/var/log/jenkins/jenkins.log"
    maxretry: 5
    findtime: 300
    bantime: 1800

# Security Scanning
aide_enabled: true
rkhunter_enabled: true
chkrootkit_enabled: true
security_audit_enabled: true

# Jenkins Security
jenkins_csrf_protection: true
jenkins_disable_cli: true
jenkins_disable_remember_me: false
jenkins_agent_protocols: ["JNLP4-connect", "Ping"]
jenkins_disable_jnlp3: true

# System Hardening
kernel_hardening_enabled: true
network_hardening_enabled: true
file_permissions_hardening: true

# Logging and Monitoring
security_log_file: "/var/log/security-audit.log"
security_log_level: "INFO"
security_alert_email: ""  # Set to enable email alerts

# Password Policies
password_min_length: 12
password_complexity_enabled: true
password_history: 5
password_max_age: 90

# Account Lockout
account_lockout_enabled: true
account_lockout_threshold: 5
account_lockout_duration: 30  # minutes
